### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by b-hass**
This PR creates some of the tests for the axioms and theorems on algebraic graphs already present in the Alga Haskell project. It also adds the partial order operator to the Graph class.

### CODE REVIEW

**Comment by snowleopard** [comment]
@b-hass Many thanks, this looks good but I have two questions.


Is this common to use `<=` for a partial order? To me, this seems like a source of potential confusion and it may be better to turn it into a total order so that graphs can be put into sets, maps, etc. Here is how the total order is defined in the Haskell library:

> The total order on graphs is defined using size-lexicographic comparison:
> * Compare the number of vertices. In case of a tie, continue.
> * Compare the sets of vertices. In case of a tie, continue.
> * Compare the number of edges. In case of a tie, continue.
> * Compare the sets of edges.

Here is the code:

http://hackage.haskell.org/package/algebraic-graphs-0.4/docs/src/Algebra.Graph.AdjacencyMap.Internal.html#line-139

The second question is: could you hook up your tests to the CI, say on Travis?

**Comment by b-hass** [comment]
Thank you for the review @snowleopard!

I agree with you and I will implement this behaviour along with the Travis CI configuration. I have one question though: I can't figure out why the comparison defined with isSubgraphOf doesn't hold as a total order. What would be the incomparable Graphs?

**Comment by snowleopard** [comment]
> What would be the incomparable Graphs?

Here is a simple example: `vertex 1` and `vertex 2` -- neither of these graphs is a subgraph of the other.

**Comment by b-hass** [comment]
Looks like this size-lexicographic comparison leads to a rather verbose and complicated implementation in Scala when compared with the code in Haskell. The comparison using Monoids is really elegant. I wonder if it would be a good idea to add the scalaz library to this project in order to have a more concise comparison function. 

It would be something like this:

```
 def <=[B >: A](that: Graph[B])(implicit ord: math.Ordering[B]): Boolean = {
        def compareSeq[T](a: Seq[T], b: Seq[T])(implicit ord: math.Ordering[T]) =
            if ((a.sorted zip b.sorted).forall(elems => ord.lteq(elems._1, elems._2))) Ordering.LT
            else Ordering.GT

        ((this.vertexCount ?|? that.vertexCount)                        |+|
        (compareSeq(this.vertexSet.toVector, that.vertexSet.toVector))  |+|
        (this.edgeCount ?|? that.edgeCount)                             |+|
        compareSeq(this.edgeSet.toVector, that.edgeSet.toVector)) == Ordering.LT
    }
```


Since Scala Sets and Iterables do not implement ordering I had to mimic Haskell's Set comparison with an auxiliary function.

**Comment by snowleopard** [comment]
@b-hass Thank you! I don't mind depending on the scalaz library if you think that would be a good way forward. Please note that I don't have a good knowledge of Scala, so I trust your judgement in this matter.

Is this PR ready to be merged?

I've just activated Travis for this repo. Do we need to make a commit to trigger the build?

**Comment by b-hass** [comment]
It's ready to be merged. The build should trigger after the merge.

**Comment by snowleopard** [comment]
Thank you, merged!

**Pull request merged**
